### ISSUE TITLE
Not streaming with Apache and PHP-FPM...

### ISSUE THREAD

**Issue by mattbryson** [licson0729/libSSE-php#21]
HI,  

I have the plugin set up running on a local dev machine fine, but when on our staging server no events are received by the browser (tested on chrome and firefox osx).

I needed to add this to the `flush` mthod...

```
    public function flush()
    {
        echo str_pad(' ', 2048, ' ');
        echo PHP_EOL;

        @ob_flush();
        @flush();
    }
```

Its on Apache and PHP-FPM and I cant see any way to disable output buffering like you can on nginx.....

is there a nicer work around to this?   chunked response maybe?

**Comment by tonyhhyip** [comment]
You should turn off the proxy buffer, so that the data would send to the client as soon as it arrive the server.

For apache please set the `ProxyIOBufferSize` and `ProxyReceiveBufferSize` in mod_proxy_fcgi to be 512 as apache force to have at least 512.

You may refer to [here](https://httpd.apache.org/docs/current/mod/mod_proxy.html).

Replacing Apache with [nginx](https://nginx.org/en) would help much as it allow completely disable the buffer.

**Comment by mattbryson** [comment]
Yeah, nginx would be better, but that will have to wait!  Cheers for the response.
